---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rssbox
data:
  REDIS_URL: "redis://redis:6379/3"
  # TWITTER_ACCESS_TOKEN: ""
  # GOOGLE_API_KEY: ""
  # VIMEO_ACCESS_TOKEN: ""
  # INSTAGRAM_SESSIONID: ""
  # SOUNDCLOUD_CLIENT_ID: ""
  # SOUNDCLOUD_CLIENT_SECRET: ""
  # TWITCH_CLIENT_ID: ""
  # TWITCHTOKEN_CLIENT_ID: ""
  # IMGUR_CLIENT_ID: ""
